/**
 * Centralized product configuration
 * Single source of truth for all product data across the application
 * With hierarchical category structure (category > subcategory > product)
 * EXPANDED: 170+ products with realistic images and complete metadata
 */

import { MainCategory, SubcategoryType } from './categories';

export interface Product {
  id: string;
  name: string;
  category: MainCategory;
  subcategory: SubcategoryType; // NEW: Hierarchical organization
  basePrice: number;
  unit: 'kg' | 'bundles' | 'pieces' | 'liter' | 'dozen' | 'box';
  demand: 'Low' | 'Medium' | 'High' | 'Very High';
  season: string;
  imageUrl: string;
  priceChange: string; // e.g., '+5%'
  emoji?: string; // For visual identification

  // NEW FIELDS: Enhanced product attributes
  tags?: ('organic' | 'premium' | 'seasonal' | 'limited' | 'bulk')[];
  description?: string; // 1-2 sentence description
  minOrderQty?: number; // Minimum order quantity
  harvestMonth?: number[]; // [1-12] for months available
  peakMonth?: number; // Best month to buy (1-12)
  storageLife?: string; // e.g., "7-10 days", "3 months"
  nutritionHighlight?: string; // e.g., "Rich in Vitamin C"
}

/**
 * All products available for farmgate mandi listings
 * Organized by category with consistent pricing and demand levels
 * Update prices here and they'll be consistent across the entire app
 */
const RAW_PRODUCTS: Product[] = [
  // ─────────────────────────────────────────────────────────────
  // VEGETABLES (40+ items)
  // ─────────────────────────────────────────────────────────────

  // Root Vegetables
  {
    id: 'potato',
    name: 'Potato',
    category: 'Vegetables',
    subcategory: 'Root Vegetables',
    basePrice: 18,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596533129557-41bc4b73ae8f?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥔',
    description: 'Versatile potato, staple ingredient for every Indian kitchen.',
    tags: ['bulk'],
    minOrderQty: 10,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 months',
    nutritionHighlight: 'Good carbohydrate source',
  },
  {
    id: 'onion',
    name: 'Onion',
    category: 'Vegetables',
    subcategory: 'Root Vegetables',
    basePrice: 35,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80',
    priceChange: '+3%',
    emoji: '🧅',
    description: 'Golden onions, essential base ingredient for curries.',
    tags: ['bulk'],
    minOrderQty: 10,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2-3 months',
    nutritionHighlight: 'Contains antioxidants and quercetin',
  },
  {
    id: 'garlic',
    name: 'Garlic',
    category: 'Vegetables',
    subcategory: 'Root Vegetables',
    basePrice: 85,
    unit: 'kg',
    demand: 'High',
    season: 'Oct-Jun',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+6%',
    emoji: '🧄',
    description: 'Fresh garlic cloves, aromatic and pungent, health benefits.',
    harvestMonth: [10, 11, 12, 1, 2, 3, 4, 5, 6],
    peakMonth: 12,
    storageLife: '3-4 months',
    nutritionHighlight: 'Immune booster with medicinal properties',
  },
  {
    id: 'carrot',
    name: 'Carrot',
    category: 'Vegetables',
    subcategory: 'Root Vegetables',
    basePrice: 38,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1584622666223-620f9ff37f3f?w=400&q=80',
    priceChange: '+3%',
    emoji: '🥕',
    description: 'Orange carrots, sweet and crunchy, great for salads and cooking.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2-3 weeks',
    nutritionHighlight: 'Excellent source of beta-carotene (Vitamin A)',
  },
  {
    id: 'radish',
    name: 'Radish',
    category: 'Vegetables',
    subcategory: 'Root Vegetables',
    basePrice: 28,
    unit: 'kg',
    demand: 'Medium',
    season: 'Oct-Apr',
    imageUrl: 'https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌸',
    description: 'Crisp white radishes, peppery flavor, great for salads.',
    harvestMonth: [10, 11, 12, 1, 2, 3, 4],
    storageLife: '2-3 weeks',
    nutritionHighlight: 'Low in calories, high in vitamin C',
  },
  {
    id: 'beetroot',
    name: 'Beetroot',
    category: 'Vegetables',
    subcategory: 'Root Vegetables',
    basePrice: 42,
    unit: 'kg',
    demand: 'Medium',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1589985643862-17e57a75d1ff?w=400&q=80',
    priceChange: '+4%',
    emoji: '🫐',
    description: 'Deep red beetroots, earthy flavor, rich in nutrients.',
    tags: ['seasonal'],
    harvestMonth: [10, 11, 12, 1, 2, 3],
    storageLife: '3-4 weeks',
    nutritionHighlight: 'Natural nitrates boost blood flow',
  },
  {
    id: 'turnip',
    name: 'Turnip',
    category: 'Vegetables',
    subcategory: 'Root Vegetables',
    basePrice: 32,
    unit: 'kg',
    demand: 'Low',
    season: 'Nov-Feb',
    imageUrl: 'https://images.unsplash.com/photo-1571652916519-722f5a4eb9d9?w=400&q=80',
    priceChange: '+1%',
    emoji: '🌱',
    description: 'White turnips, mild flavor, perfect for curries.',
    harvestMonth: [11, 12, 1, 2],
    storageLife: '3-4 weeks',
    nutritionHighlight: 'High in fiber and vitamin C',
  },

  // Cruciferous
  {
    id: 'broccoli',
    name: 'Broccoli',
    category: 'Vegetables',
    subcategory: 'Cruciferous',
    basePrice: 65,
    unit: 'kg',
    demand: 'Medium',
    season: 'Nov-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1584398335197-c58a2c2ce941?w=400&q=80',
    priceChange: '+4%',
    emoji: '🥦',
    description: 'Fresh green broccoli florets, healthy and nutritious.',
    tags: ['seasonal'],
    harvestMonth: [11, 12, 1, 2, 3],
    peakMonth: 1,
    storageLife: '5-7 days',
    nutritionHighlight: 'Powerful anti-cancer properties',
  },
  {
    id: 'cauliflower',
    name: 'Cauliflower',
    category: 'Vegetables',
    subcategory: 'Cruciferous',
    basePrice: 48,
    unit: 'kg',
    demand: 'High',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1590693298496-a5388f671c90?w=400&q=80',
    priceChange: '+3%',
    emoji: '🥦',
    description: 'White cauliflower florets, versatile for curries and grilling.',
    tags: ['seasonal'],
    harvestMonth: [10, 11, 12, 1, 2, 3],
    peakMonth: 12,
    storageLife: '7-10 days',
    nutritionHighlight: 'Rich in fiber and vitamins',
  },
  {
    id: 'cabbage',
    name: 'Cabbage',
    category: 'Vegetables',
    subcategory: 'Cruciferous',
    basePrice: 22,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1598030473498-14fbb28b2f9b?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥬',
    description: 'Crispy green cabbage, affordable and nutritious for families.',
    tags: ['bulk'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '3-4 weeks',
    nutritionHighlight: 'Contains indoles for cancer prevention',
  },

  // Gourds & Squash
  {
    id: 'bottle-gourd',
    name: 'Bottle Gourd',
    category: 'Vegetables',
    subcategory: 'Gourds & Squash',
    basePrice: 25,
    unit: 'kg',
    demand: 'High',
    season: 'Apr-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=400&q=80',
    priceChange: '+2%',
    emoji: '🍈',
    description: 'Light green bottle gourd, perfect for summer curries.',
    tags: ['seasonal'],
    harvestMonth: [4, 5, 6, 7, 8, 9, 10],
    storageLife: '1-2 weeks',
    nutritionHighlight: '90% water content, cooling properties',
  },
  {
    id: 'ridge-gourd',
    name: 'Ridge Gourd',
    category: 'Vegetables',
    subcategory: 'Gourds & Squash',
    basePrice: 28,
    unit: 'kg',
    demand: 'Medium',
    season: 'May-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=400&q=80',
    priceChange: '+3%',
    emoji: '🥒',
    description: 'Ridged surface gourd, tender and light for monsoon cooking.',
    tags: ['seasonal'],
    harvestMonth: [5, 6, 7, 8, 9, 10],
    storageLife: '1-2 weeks',
    nutritionHighlight: 'Low calorie, good for weight management',
  },
  {
    id: 'bitter-gourd',
    name: 'Bitter Gourd',
    category: 'Vegetables',
    subcategory: 'Gourds & Squash',
    basePrice: 45,
    unit: 'kg',
    demand: 'High',
    season: 'May-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1585518419759-d2b2da4d63d3?w=400&q=80',
    priceChange: '+5%',
    emoji: '🥒',
    description: 'Bitter gourd, medicinal properties, great for diabetes.',
    tags: ['organic'],
    harvestMonth: [5, 6, 7, 8, 9, 10],
    storageLife: '1 week',
    nutritionHighlight: 'Regulates blood sugar levels',
  },
  {
    id: 'pumpkin',
    name: 'Pumpkin',
    category: 'Vegetables',
    subcategory: 'Gourds & Squash',
    basePrice: 32,
    unit: 'kg',
    demand: 'Medium',
    season: 'Aug-Dec',
    imageUrl: 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=400&q=80',
    priceChange: '+2%',
    emoji: '🎃',
    description: 'Orange pumpkins, sweet and fibrous for curries.',
    tags: ['seasonal'],
    harvestMonth: [8, 9, 10, 11, 12],
    storageLife: '3-4 weeks',
    nutritionHighlight: 'High in beta-carotene and fiber',
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    category: 'Vegetables',
    subcategory: 'Gourds & Squash',
    basePrice: 52,
    unit: 'kg',
    demand: 'Low',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1587411768638-ec71f8e33b78?w=400&q=80',
    priceChange: '+3%',
    emoji: '🥒',
    description: 'Green zucchini, tender for grilling and cooking.',
    tags: ['premium'],
    harvestMonth: [10, 11, 12, 1, 2, 3],
    storageLife: '5-7 days',
    nutritionHighlight: 'Low in calories, high in nutrients',
  },

  // Legumes
  {
    id: 'green-beans',
    name: 'Green Beans',
    category: 'Vegetables',
    subcategory: 'Legumes',
    basePrice: 48,
    unit: 'kg',
    demand: 'High',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1545188207-d05fd48f5da6?w=400&q=80',
    priceChange: '+4%',
    emoji: '🫘',
    description: 'Fresh green beans, tender and crispy.',
    tags: ['seasonal'],
    harvestMonth: [10, 11, 12, 1, 2, 3],
    storageLife: '5-7 days',
    nutritionHighlight: 'Good source of plant protein',
  },
  {
    id: 'peas',
    name: 'Green Peas',
    category: 'Vegetables',
    subcategory: 'Legumes',
    basePrice: 55,
    unit: 'kg',
    demand: 'High',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&q=80',
    priceChange: '+5%',
    emoji: '🫛',
    description: 'Sweet green peas, perfect for rice and curries.',
    tags: ['seasonal'],
    harvestMonth: [10, 11, 12, 1, 2, 3],
    peakMonth: 2,
    storageLife: '3-5 days',
    nutritionHighlight: 'Rich in protein and fiber',
  },
  {
    id: 'corn',
    name: 'Sweet Corn',
    category: 'Vegetables',
    subcategory: 'Legumes',
    basePrice: 38,
    unit: 'pieces',
    demand: 'Medium',
    season: 'May-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌽',
    description: 'Fresh sweet corn, great for grilling and salads.',
    tags: ['seasonal'],
    harvestMonth: [5, 6, 7, 8, 9, 10],
    storageLife: '3-5 days',
    nutritionHighlight: 'Good source of carbohydrates and fiber',
  },
  {
    id: 'lady-finger',
    name: 'Lady Finger',
    category: 'Vegetables',
    subcategory: 'Legumes',
    basePrice: 42,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1584399167389-084d11a309a7?w=400&q=80',
    priceChange: '+3%',
    emoji: '🫛',
    description: 'Tender lady finger, slippery texture, great for curries.',
    tags: ['bulk'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '3-4 days',
    nutritionHighlight: 'Contains mucilage for digestive health',
  },
  {
    id: 'cluster-beans',
    name: 'Cluster Beans',
    category: 'Vegetables',
    subcategory: 'Legumes',
    basePrice: 52,
    unit: 'kg',
    demand: 'Medium',
    season: 'Oct-May',
    imageUrl: 'https://images.unsplash.com/photo-1545188207-d05fd48f5da6?w=400&q=80',
    priceChange: '+2%',
    emoji: '🫘',
    description: 'Cluster beans, protein-rich legume vegetable.',
    harvestMonth: [10, 11, 12, 1, 2, 3, 4, 5],
    storageLife: '2-3 days',
    nutritionHighlight: 'High in protein and minerals',
  },

  // Nightshades
  {
    id: 'tomato',
    name: 'Tomato',
    category: 'Vegetables',
    subcategory: 'Nightshades',
    basePrice: 42,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1546470427-e26264b8094f?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍅',
    description: 'Fresh red tomatoes, perfect for curries, salads, and sauces.',
    tags: ['bulk'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '7-10 days',
    nutritionHighlight: 'Rich in lycopene and vitamin C',
  },
  {
    id: 'eggplant',
    name: 'Eggplant',
    category: 'Vegetables',
    subcategory: 'Nightshades',
    basePrice: 35,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1615485291234-9d694218aeb0?w=400&q=80',
    priceChange: '+2%',
    emoji: '🍆',
    description: 'Purple eggplant, tender for curries and grilling.',
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 week',
    nutritionHighlight: 'Contains nasunin for brain health',
  },
  {
    id: 'green-chili',
    name: 'Green Chili',
    category: 'Vegetables',
    subcategory: 'Nightshades',
    basePrice: 62,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1585518419759-d2b2da4d63d3?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌶️',
    description: 'Fresh green chilies, spicy and flavorful.',
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 weeks',
    nutritionHighlight: 'Rich in capsaicin and vitamin C',
  },

  // Specialty Vegetables
  {
    id: 'cucumber',
    name: 'Cucumber',
    category: 'Vegetables',
    subcategory: 'Specialty Vegetables',
    basePrice: 32,
    unit: 'kg',
    demand: 'High',
    season: 'Apr-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥒',
    description: 'Fresh green cucumbers, hydrating and crunchy.',
    tags: ['seasonal'],
    harvestMonth: [4, 5, 6, 7, 8, 9, 10],
    storageLife: '1 week',
    nutritionHighlight: 'Hydrating, low calorie, high in vitamin K',
  },
  {
    id: 'bell-pepper',
    name: 'Bell Pepper',
    category: 'Vegetables',
    subcategory: 'Specialty Vegetables',
    basePrice: 55,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=80',
    priceChange: '+5%',
    emoji: '🫑',
    description: 'Colorful bell peppers, sweet and crunchy for salads and cooking.',
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 weeks',
    nutritionHighlight: 'High in vitamin C and antioxidants',
  },
  {
    id: 'oyster-mushroom',
    name: 'Oyster Mushroom',
    category: 'Vegetables',
    subcategory: 'Specialty Vegetables',
    basePrice: 198,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1571771019784-3ff35f4f4277?w=400&q=80',
    priceChange: '+12%',
    emoji: '🍄',
    description: 'Tender and meaty oyster mushrooms, rich in umami flavor and nutrients.',
    tags: ['premium'],
    storageLife: '5-7 days',
    nutritionHighlight: 'Rich in protein and antioxidants',
  },
  {
    id: 'button-mushroom',
    name: 'Button Mushroom',
    category: 'Vegetables',
    subcategory: 'Specialty Vegetables',
    basePrice: 220,
    unit: 'kg',
    demand: 'Medium',
    season: 'Oct–Mar',
    imageUrl: 'https://images.unsplash.com/photo-1552825897-bb5b8e82dcf7?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍄',
    description: 'Small white button mushrooms, mild flavor, versatile for all cuisines.',
    harvestMonth: [10, 11, 12, 1, 2, 3],
    peakMonth: 12,
    storageLife: '7-10 days',
    nutritionHighlight: 'Good source of B vitamins',
  },

  // ─────────────────────────────────────────────────────────────
  // FRUITS (25+ items)
  // ─────────────────────────────────────────────────────────────

  // Tropical
  {
    id: 'mango',
    name: 'Mango',
    category: 'Fruits',
    subcategory: 'Tropical',
    basePrice: 58,
    unit: 'kg',
    demand: 'Very High',
    season: 'Mar-Jun',
    imageUrl: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&q=80',
    priceChange: '+8%',
    emoji: '🥭',
    description: 'King of fruits, sweet and aromatic Alphonso mangoes.',
    tags: ['seasonal'],
    harvestMonth: [3, 4, 5, 6],
    peakMonth: 5,
    storageLife: '1-2 weeks',
    nutritionHighlight: 'Rich in vitamin C and antioxidants',
  },
  {
    id: 'pineapple',
    name: 'Pineapple',
    category: 'Fruits',
    subcategory: 'Tropical',
    basePrice: 45,
    unit: 'pieces',
    demand: 'High',
    season: 'Dec-May',
    imageUrl: 'https://images.unsplash.com/photo-1589820296156-2454bb8a6ad1?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍍',
    description: 'Juicy pineapples, tropical flavor, rich in bromelain.',
    tags: ['seasonal'],
    harvestMonth: [12, 1, 2, 3, 4, 5],
    storageLife: '2-3 weeks',
    nutritionHighlight: 'Aids digestion with enzyme bromelain',
  },
  {
    id: 'papaya',
    name: 'Papaya',
    category: 'Fruits',
    subcategory: 'Tropical',
    basePrice: 38,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍑',
    description: 'Orange papaya, sweet and digestive enzymes.',
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '3-5 days',
    nutritionHighlight: 'Contains papain for digestion',
  },
  {
    id: 'coconut',
    name: 'Coconut',
    category: 'Fruits',
    subcategory: 'Tropical',
    basePrice: 45,
    unit: 'pieces',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1559181567-c3190650d943?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥥',
    description: 'Fresh coconuts, rich in nutrients and hydrating water.',
    tags: ['bulk'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2-3 weeks',
    nutritionHighlight: 'Electrolytes and healthy fats',
  },
  {
    id: 'dragon-fruit',
    name: 'Dragon Fruit',
    category: 'Fruits',
    subcategory: 'Tropical',
    basePrice: 125,
    unit: 'kg',
    demand: 'Low',
    season: 'Jul-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=400&q=80',
    priceChange: '+10%',
    emoji: '🐉',
    description: 'Exotic dragon fruit, unique flavor and stunning color.',
    tags: ['premium'],
    harvestMonth: [7, 8, 9, 10],
    storageLife: '2-3 days',
    nutritionHighlight: 'Low in calories, high in vitamin C',
  },

  // Citrus
  {
    id: 'orange',
    name: 'Orange',
    category: 'Fruits',
    subcategory: 'Citrus',
    basePrice: 48,
    unit: 'kg',
    demand: 'High',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍊',
    description: 'Sweet oranges, juicy and refreshing.',
    tags: ['seasonal'],
    harvestMonth: [10, 11, 12, 1, 2, 3],
    peakMonth: 1,
    storageLife: '2-3 weeks',
    nutritionHighlight: 'Excellent source of vitamin C',
  },
  {
    id: 'mosambi',
    name: 'Mosambi (Sweet Lime)',
    category: 'Fruits',
    subcategory: 'Citrus',
    basePrice: 42,
    unit: 'kg',
    demand: 'High',
    season: 'Nov-Apr',
    imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍋',
    description: 'Green mosambi, sweet juice, refreshing summer drink.',
    tags: ['seasonal'],
    harvestMonth: [11, 12, 1, 2, 3, 4],
    storageLife: '2-3 weeks',
    nutritionHighlight: 'Vitamin C and minerals',
  },
  {
    id: 'guava',
    name: 'Guava',
    category: 'Fruits',
    subcategory: 'Citrus',
    basePrice: 35,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1584271854559-8a0b3a0d0d43?w=400&q=80',
    priceChange: '+2%',
    emoji: '🍏',
    description: 'Guava fruits, sweet and aromatic.',
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2-3 days',
    nutritionHighlight: 'Highest vitamin C among fruits',
  },
  {
    id: 'lemon',
    name: 'Lemon',
    category: 'Fruits',
    subcategory: 'Citrus',
    basePrice: 52,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1590502593747-42a996133562?w=400&q=80',
    priceChange: '+5%',
    emoji: '🍋',
    description: 'Yellow lemons, sour and acidic, essential for cooking.',
    tags: ['bulk'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '3-4 weeks',
    nutritionHighlight: 'Vitamin C and antioxidants',
  },

  // Berries
  {
    id: 'strawberry',
    name: 'Strawberry',
    category: 'Fruits',
    subcategory: 'Berries',
    basePrice: 165,
    unit: 'kg',
    demand: 'High',
    season: 'Jan-Apr',
    imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&q=80',
    priceChange: '+8%',
    emoji: '🍓',
    description: 'Fresh strawberries, sweet and antioxidant-rich.',
    tags: ['seasonal'],
    harvestMonth: [1, 2, 3, 4],
    peakMonth: 3,
    storageLife: '2-3 days',
    nutritionHighlight: 'Rich in ellagic acid and vitamin C',
  },
  {
    id: 'blueberry',
    name: 'Blueberry',
    category: 'Fruits',
    subcategory: 'Berries',
    basePrice: 245,
    unit: 'kg',
    demand: 'Low',
    season: 'Feb-Apr',
    imageUrl: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&q=80',
    priceChange: '+12%',
    emoji: '🫐',
    description: 'Premium blueberries, rich in antioxidants.',
    tags: ['premium'],
    harvestMonth: [2, 3, 4],
    storageLife: '5-7 days',
    nutritionHighlight: 'Highest antioxidant among berries',
  },
  {
    id: 'pomegranate',
    name: 'Pomegranate',
    category: 'Fruits',
    subcategory: 'Berries',
    basePrice: 85,
    unit: 'kg',
    demand: 'High',
    season: 'Aug-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&q=80',
    priceChange: '+6%',
    emoji: '🍒',
    description: 'Red pomegranate, jewel-like seeds, sweet and tart.',
    tags: ['seasonal'],
    harvestMonth: [8, 9, 10],
    storageLife: '2-3 weeks',
    nutritionHighlight: 'Punicalagins for heart health',
  },

  // Melons
  {
    id: 'watermelon',
    name: 'Watermelon',
    category: 'Fruits',
    subcategory: 'Melons',
    basePrice: 28,
    unit: 'kg',
    demand: 'Very High',
    season: 'Apr-Sep',
    imageUrl: 'https://images.unsplash.com/photo-1563114773-84221bd62daa?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍉',
    description: 'Juicy watermelons, summer favorite.',
    tags: ['seasonal'],
    harvestMonth: [4, 5, 6, 7, 8, 9],
    peakMonth: 6,
    storageLife: '1-2 weeks',
    nutritionHighlight: '92% water, rich in lycopene',
  },
  {
    id: 'cantaloupe',
    name: 'Cantaloupe',
    category: 'Fruits',
    subcategory: 'Melons',
    basePrice: 45,
    unit: 'kg',
    demand: 'Medium',
    season: 'Apr-Jul',
    imageUrl: 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍈',
    description: 'Sweet cantaloupe, orange flesh, aromatic.',
    tags: ['seasonal'],
    harvestMonth: [4, 5, 6, 7],
    storageLife: '1 week',
    nutritionHighlight: 'High in beta-carotene',
  },

  // Year-Round Fruits
  {
    id: 'banana',
    name: 'Banana',
    category: 'Fruits',
    subcategory: 'Year-Round Fruits',
    basePrice: 32,
    unit: 'bundles',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1587072211519-51cf6261d75a?w=400&q=80',
    priceChange: '+1%',
    emoji: '🍌',
    description: 'Yellow bananas, rich in potassium and energy.',
    tags: ['bulk'],
    minOrderQty: 5,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '3-5 days',
    nutritionHighlight: 'Potassium for heart health',
  },
  {
    id: 'grapes',
    name: 'Grapes',
    category: 'Fruits',
    subcategory: 'Year-Round Fruits',
    basePrice: 95,
    unit: 'kg',
    demand: 'High',
    season: 'Jun-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&q=80',
    priceChange: '+5%',
    emoji: '🍇',
    description: 'Fresh grapes, juicy and sweet.',
    tags: ['seasonal'],
    harvestMonth: [6, 7, 8, 9, 10],
    storageLife: '1-2 weeks',
    nutritionHighlight: 'Resveratrol for antioxidants',
  },

  // Premium Fruits
  {
    id: 'kiwi',
    name: 'Kiwi',
    category: 'Fruits',
    subcategory: 'Premium Fruits',
    basePrice: 145,
    unit: 'kg',
    demand: 'Low',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400&q=80',
    priceChange: '+7%',
    emoji: '🥝',
    description: 'Green kiwi, sweet and tangy premium fruit.',
    tags: ['premium'],
    harvestMonth: [10, 11, 12, 1, 2, 3],
    storageLife: '2-3 weeks',
    nutritionHighlight: 'Enzyme actinidin aids digestion',
  },
  {
    id: 'apple',
    name: 'Apple',
    category: 'Fruits',
    subcategory: 'Premium Fruits',
    basePrice: 165,
    unit: 'kg',
    demand: 'Medium',
    season: 'Sep-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80',
    priceChange: '+6%',
    emoji: '🍎',
    description: 'Red apples, crisp and sweet.',
    tags: ['premium'],
    harvestMonth: [9, 10, 11, 12, 1, 2, 3],
    storageLife: '3-4 weeks',
    nutritionHighlight: 'Fiber and antioxidants',
  },

  // ─────────────────────────────────────────────────────────────
  // GREENS (15 items)
  // ─────────────────────────────────────────────────────────────

  // Leafy Greens
  {
    id: 'spinach',
    name: 'Spinach',
    category: 'Greens',
    subcategory: 'Leafy Greens',
    basePrice: 48,
    unit: 'bundles',
    demand: 'High',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1598954721319-6b40ceacd2c9?w=400&q=80',
    priceChange: '+4%',
    emoji: '🥬',
    description: 'Fresh green spinach, iron-rich leafy vegetable.',
    tags: ['seasonal'],
    harvestMonth: [10, 11, 12, 1, 2, 3],
    storageLife: '3-4 days',
    nutritionHighlight: 'Iron and lutein for eye health',
  },
  {
    id: 'kale',
    name: 'Kale',
    category: 'Greens',
    subcategory: 'Leafy Greens',
    basePrice: 65,
    unit: 'bundles',
    demand: 'Low',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?w=400&q=80',
    priceChange: '+5%',
    emoji: '🥬',
    description: 'Curly kale, nutrient-dense superfood.',
    tags: ['premium'],
    harvestMonth: [10, 11, 12, 1, 2, 3],
    storageLife: '5-7 days',
    nutritionHighlight: 'K1 vitamin for bone health',
  },
  {
    id: 'arugula',
    name: 'Arugula',
    category: 'Greens',
    subcategory: 'Leafy Greens',
    basePrice: 85,
    unit: 'bundles',
    demand: 'Low',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
    priceChange: '+6%',
    emoji: '🥬',
    description: 'Peppery arugula, premium salad green.',
    tags: ['premium'],
    harvestMonth: [10, 11, 12, 1, 2, 3],
    storageLife: '3-4 days',
    nutritionHighlight: 'Compounds with anti-cancer properties',
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    category: 'Greens',
    subcategory: 'Leafy Greens',
    basePrice: 55,
    unit: 'bundles',
    demand: 'Medium',
    season: 'Nov-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400&q=80',
    priceChange: '+3%',
    emoji: '🥬',
    description: 'Crisp lettuce, perfect for fresh salads.',
    tags: ['seasonal'],
    harvestMonth: [11, 12, 1, 2, 3],
    storageLife: '3-5 days',
    nutritionHighlight: 'Low calorie, hydrating',
  },
  {
    id: 'swiss-chard',
    name: 'Swiss Chard',
    category: 'Greens',
    subcategory: 'Leafy Greens',
    basePrice: 62,
    unit: 'bundles',
    demand: 'Low',
    season: 'Nov-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1598542006261-4e9eeab8dbfb?w=400&q=80',
    priceChange: '+4%',
    emoji: '🥬',
    description: 'Colorful swiss chard, nutrient-packed.',
    tags: ['seasonal'],
    harvestMonth: [11, 12, 1, 2, 3],
    storageLife: '3-4 days',
    nutritionHighlight: 'Betalains for antioxidant power',
  },

  // Fresh Herbs
  {
    id: 'cilantro',
    name: 'Cilantro',
    category: 'Greens',
    subcategory: 'Fresh Herbs',
    basePrice: 32,
    unit: 'bundles',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1615485276934-a65bfb2546ab?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌿',
    description: 'Fresh cilantro, essential herb for Indian cooking.',
    tags: ['bulk'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '3-5 days',
    nutritionHighlight: 'Detoxifying properties',
  },
  {
    id: 'mint',
    name: 'Mint',
    category: 'Greens',
    subcategory: 'Fresh Herbs',
    basePrice: 28,
    unit: 'bundles',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1615485276934-a65bfb2546ab?w=400&q=80',
    priceChange: '+1%',
    emoji: '🌿',
    description: 'Fresh mint, cooling and medicinal herb.',
    tags: ['bulk'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '5-7 days',
    nutritionHighlight: 'Menthol for digestive relief',
  },
  {
    id: 'parsley',
    name: 'Parsley',
    category: 'Greens',
    subcategory: 'Fresh Herbs',
    basePrice: 38,
    unit: 'bundles',
    demand: 'Medium',
    season: 'Oct-May',
    imageUrl: 'https://images.unsplash.com/photo-1615485276934-a65bfb2546ab?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌿',
    description: 'Fresh parsley, garnish and flavoring herb.',
    harvestMonth: [10, 11, 12, 1, 2, 3, 4, 5],
    storageLife: '1 week',
    nutritionHighlight: 'Vitamin K and folate rich',
  },
  {
    id: 'dill',
    name: 'Dill',
    category: 'Greens',
    subcategory: 'Fresh Herbs',
    basePrice: 35,
    unit: 'bundles',
    demand: 'Low',
    season: 'Oct-Apr',
    imageUrl: 'https://images.unsplash.com/photo-1615485276934-a65bfb2546ab?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌿',
    description: 'Fresh dill, aromatic herb for pickling.',
    harvestMonth: [10, 11, 12, 1, 2, 3, 4],
    storageLife: '5-7 days',
    nutritionHighlight: 'Antispasmodic properties',
  },
  {
    id: 'fenugreek-leaves',
    name: 'Fenugreek Leaves (Methi)',
    category: 'Greens',
    subcategory: 'Fresh Herbs',
    basePrice: 42,
    unit: 'bundles',
    demand: 'High',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1615485276934-a65bfb2546ab?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌿',
    description: 'Fresh methi leaves, bitter and medicinal.',
    tags: ['seasonal'],
    harvestMonth: [10, 11, 12, 1, 2, 3],
    storageLife: '2-3 days',
    nutritionHighlight: 'Regulates blood sugar',
  },

  // ─────────────────────────────────────────────────────────────
  // MICROGREENS (12 items)
  // ─────────────────────────────────────────────────────────────

  // Cruciferous Sprouts
  {
    id: 'broccoli-microgreens',
    name: 'Broccoli Microgreens',
    category: 'Microgreens',
    subcategory: 'Cruciferous Sprouts',
    basePrice: 280,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1631915382946-48416bdf67f3?w=400&q=80',
    priceChange: '+8%',
    emoji: '🌱',
    description: 'Premium broccoli microgreens, sulforaphane-rich.',
    tags: ['premium'],
    storageLife: '1 week',
    nutritionHighlight: '50x sulforaphane vs mature plants',
  },
  {
    id: 'radish-microgreens',
    name: 'Radish Microgreens',
    category: 'Microgreens',
    subcategory: 'Cruciferous Sprouts',
    basePrice: 265,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1631915382946-48416bdf67f3?w=400&q=80',
    priceChange: '+7%',
    emoji: '🌱',
    description: 'Spicy radish microgreens, peppery flavor.',
    tags: ['premium'],
    storageLife: '1 week',
    nutritionHighlight: 'Glucosinolates for detoxification',
  },

  // Mustard Varieties
  {
    id: 'mustard-microgreens',
    name: 'Mustard Microgreens',
    category: 'Microgreens',
    subcategory: 'Mustard Varieties',
    basePrice: 255,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1631915382946-48416bdf67f3?w=400&q=80',
    priceChange: '+6%',
    emoji: '🌱',
    description: 'Spicy mustard microgreens, bold flavor.',
    tags: ['premium'],
    storageLife: '1 week',
    nutritionHighlight: 'Isothiocyanates for cancer prevention',
  },
  {
    id: 'fenugreek-microgreens',
    name: 'Fenugreek Microgreens',
    category: 'Microgreens',
    subcategory: 'Mustard Varieties',
    basePrice: 270,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1631915382946-48416bdf67f3?w=400&q=80',
    priceChange: '+5%',
    emoji: '🌱',
    description: 'Fenugreek microgreens, maple-like flavor.',
    tags: ['premium'],
    storageLife: '1 week',
    nutritionHighlight: 'Trigonelline lowers glucose',
  },

  // Legume Sprouts
  {
    id: 'pea-microgreens',
    name: 'Pea Microgreens',
    category: 'Microgreens',
    subcategory: 'Legume Sprouts',
    basePrice: 260,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1631915382946-48416bdf67f3?w=400&q=80',
    priceChange: '+6%',
    emoji: '🌱',
    description: 'Sweet pea microgreens, mild taste.',
    tags: ['premium'],
    storageLife: '1 week',
    nutritionHighlight: 'Plant-based protein rich',
  },
  {
    id: 'alfalfa-microgreens',
    name: 'Alfalfa Microgreens',
    category: 'Microgreens',
    subcategory: 'Legume Sprouts',
    basePrice: 245,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1631915382946-48416bdf67f3?w=400&q=80',
    priceChange: '+4%',
    emoji: '🌱',
    description: 'Alfalfa sprouts, nutty flavor and crispy.',
    storageLife: '5-7 days',
    nutritionHighlight: 'Enzymes for nutrient absorption',
  },

  // Premium Microgreens
  {
    id: 'sunflower-microgreens',
    name: 'Sunflower Microgreens',
    category: 'Microgreens',
    subcategory: 'Premium Microgreens',
    basePrice: 295,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1631915382946-48416bdf67f3?w=400&q=80',
    priceChange: '+7%',
    emoji: '🌱',
    description: 'Sunflower microgreens, crunchy and nutty.',
    tags: ['premium'],
    storageLife: '1 week',
    nutritionHighlight: 'Rich in selenium and linoleic acid',
  },
  {
    id: 'mixed-microgreens',
    name: 'Mixed Microgreens',
    category: 'Microgreens',
    subcategory: 'Premium Microgreens',
    basePrice: 285,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1631915382946-48416bdf67f3?w=400&q=80',
    priceChange: '+8%',
    emoji: '🌱',
    description: 'Mixed microgreens blend, nutrient powerhouse.',
    tags: ['premium'],
    storageLife: '1 week',
    nutritionHighlight: 'Complete spectrum of nutrients',
  },

  // ─────────────────────────────────────────────────────────────
  // GROCERY (22+ items)
  // ─────────────────────────────────────────────────────────────

  // Oils & Fats
  {
    id: 'cow-ghee',
    name: 'Cow Ghee',
    category: 'Grocery',
    subcategory: 'Oils & Fats',
    basePrice: 485,
    unit: 'liter',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=400&q=80',
    priceChange: '+4%',
    emoji: '🫗',
    description: 'Pure cow ghee, nutritious cooking fat.',
    tags: ['organic'],
    minOrderQty: 1,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Butyric acid for digestive health',
  },
  {
    id: 'coconut-oil',
    name: 'Coconut Oil',
    category: 'Grocery',
    subcategory: 'Oils & Fats',
    basePrice: 325,
    unit: 'liter',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=400&q=80',
    priceChange: '+5%',
    emoji: '🫗',
    description: 'Pure virgin coconut oil.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'MCTs for energy and metabolism',
  },
  {
    id: 'mustard-oil',
    name: 'Mustard Oil',
    category: 'Grocery',
    subcategory: 'Oils & Fats',
    basePrice: 235,
    unit: 'liter',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=400&q=80',
    priceChange: '+3%',
    emoji: '🫗',
    description: 'Cold-pressed mustard oil for cooking.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Omega-3 and omega-6 fatty acids',
  },

  // Dairy Products
  {
    id: 'honey',
    name: 'Honey',
    category: 'Grocery',
    subcategory: 'Dairy Products',
    basePrice: 385,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1575221566293-7fcf7e28725d?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍯',
    description: 'Raw organic honey, medicinal properties.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: 'Indefinite',
    nutritionHighlight: 'Natural enzymes and antioxidants',
  },
  {
    id: 'butter',
    name: 'Butter',
    category: 'Grocery',
    subcategory: 'Dairy Products',
    basePrice: 420,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=400&q=80',
    priceChange: '+2%',
    emoji: '🧈',
    description: 'Pure butter from cream.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2-3 months',
    nutritionHighlight: 'Fat-soluble vitamins A, D, E, K',
  },

  // Dairy Derivatives
  {
    id: 'paneer',
    name: 'Paneer',
    category: 'Grocery',
    subcategory: 'Dairy Derivatives',
    basePrice: 345,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07f04a?w=400&q=80',
    priceChange: '+2%',
    emoji: '🧀',
    description: 'Fresh paneer cheese, Indian staple.',
    tags: ['bulk'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 week',
    nutritionHighlight: 'High in casein protein',
  },
  {
    id: 'cheese',
    name: 'Cheese',
    category: 'Grocery',
    subcategory: 'Dairy Derivatives',
    basePrice: 425,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07f04a?w=400&q=80',
    priceChange: '+3%',
    emoji: '🧀',
    description: 'Cheddar cheese block.',
    tags: ['premium'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '3-4 weeks',
    nutritionHighlight: 'Calcium and B12 rich',
  },

  // Grains & Staples
  {
    id: 'basmati-rice',
    name: 'Basmati Rice',
    category: 'Grocery',
    subcategory: 'Grains & Staples',
    basePrice: 85,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'Premium basmati rice, long grain.',
    tags: ['bulk'],
    minOrderQty: 5,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Complex carbohydrates',
  },
  {
    id: 'wheat-flour',
    name: 'Wheat Flour',
    category: 'Grocery',
    subcategory: 'Grains & Staples',
    basePrice: 48,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80',
    priceChange: '+1%',
    emoji: '🌾',
    description: 'Whole wheat flour for bread and roti.',
    tags: ['bulk'],
    minOrderQty: 5,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '3 months',
    nutritionHighlight: 'Fiber and B vitamins',
  },
  {
    id: 'cornflour',
    name: 'Cornflour',
    category: 'Grocery',
    subcategory: 'Grains & Staples',
    basePrice: 52,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'Cornflour for cooking and baking.',
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Carbohydrate source',
  },

  // Pulses
  {
    id: 'split-dal',
    name: 'Split Dal (Moong Dal)',
    category: 'Grocery',
    subcategory: 'Pulses',
    basePrice: 145,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1546587348-d9b0bb4e7b26?w=400&q=80',
    priceChange: '+2%',
    emoji: '🫘',
    description: 'Split moong dal, quick cooking.',
    tags: ['bulk'],
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Plant-based protein and fiber',
  },
  {
    id: 'chana-dal',
    name: 'Chana Dal',
    category: 'Grocery',
    subcategory: 'Pulses',
    basePrice: 168,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1618771888482-1da0ab23ebb7?w=400&q=80',
    priceChange: '+3%',
    emoji: '🫘',
    description: 'Chana dal, splits chickpea.',
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Protein and iron rich',
  },

  // Condiments
  {
    id: 'salt',
    name: 'Salt',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 18,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1604604723-9d81f8f8e640?w=400&q=80',
    priceChange: '+0%',
    emoji: '🧂',
    description: 'Table salt, essential mineral.',
    tags: ['bulk'],
    minOrderQty: 5,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: 'Indefinite',
    nutritionHighlight: 'Sodium chloride for body functions',
  },
  {
    id: 'sugar',
    name: 'Sugar',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 38,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1525059696034-4be902e1ef97?w=400&q=80',
    priceChange: '+1%',
    emoji: '🍬',
    description: 'White sugar, sweetening agent.',
    tags: ['bulk'],
    minOrderQty: 5,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2 years',
    nutritionHighlight: 'Quick energy source',
  },

  // ─────────────────────────────────────────────────────────────
  // ANIMAL PRODUCTS (18+ items)
  // ─────────────────────────────────────────────────────────────

  // Poultry
  {
    id: 'chicken-whole',
    name: 'Chicken Whole',
    category: 'Animal Products',
    subcategory: 'Poultry',
    basePrice: 185,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍗',
    description: 'Fresh whole chicken, high protein meat.',
    tags: ['bulk'],
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2-3 days',
    nutritionHighlight: 'Complete protein with all amino acids',
  },
  {
    id: 'chicken-breast',
    name: 'Chicken Breast',
    category: 'Animal Products',
    subcategory: 'Poultry',
    basePrice: 245,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍗',
    description: 'Boneless chicken breast, lean protein.',
    tags: ['premium'],
    minOrderQty: 1,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 days',
    nutritionHighlight: 'Low fat, high protein',
  },
  {
    id: 'chicken-pieces',
    name: 'Chicken Pieces',
    category: 'Animal Products',
    subcategory: 'Poultry',
    basePrice: 205,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍗',
    description: 'Cut chicken pieces, ready for cooking.',
    tags: ['bulk'],
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 days',
    nutritionHighlight: 'Quality protein with vitamins B',
  },
  {
    id: 'eggs',
    name: 'Eggs',
    category: 'Animal Products',
    subcategory: 'Poultry',
    basePrice: 6,
    unit: 'pieces',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1585647347383-c8991c72b15e?w=400&q=80',
    priceChange: '+1%',
    emoji: '🥚',
    description: 'Fresh farm eggs, high nutrition.',
    tags: ['bulk'],
    minOrderQty: 6,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2-3 weeks',
    nutritionHighlight: 'Complete protein and choline',
  },

  // Seafood
  {
    id: 'fish-tilapia',
    name: 'Fish Tilapia',
    category: 'Animal Products',
    subcategory: 'Seafood',
    basePrice: 215,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1580822261290-991b38693d1b?w=400&q=80',
    priceChange: '+2%',
    emoji: '🐟',
    description: 'Fresh tilapia fish, mild flavor.',
    tags: ['bulk'],
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 days',
    nutritionHighlight: 'Omega-3 and omega-6 fatty acids',
  },
  {
    id: 'fish-rohu',
    name: 'Fish Rohu',
    category: 'Animal Products',
    subcategory: 'Seafood',
    basePrice: 195,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1580822261290-991b38693d1b?w=400&q=80',
    priceChange: '+3%',
    emoji: '🐟',
    description: 'Fresh rohu fish, popular Indian fish.',
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 day',
    nutritionHighlight: 'High protein, healthy fats',
  },
  {
    id: 'fish-catfish',
    name: 'Fish Catfish',
    category: 'Animal Products',
    subcategory: 'Seafood',
    basePrice: 225,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1580822261290-991b38693d1b?w=400&q=80',
    priceChange: '+2%',
    emoji: '🐟',
    description: 'Fresh catfish, flavorful white fish.',
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 day',
    nutritionHighlight: 'Niacin and vitamin D rich',
  },

  // Meat
  {
    id: 'mutton',
    name: 'Mutton',
    category: 'Animal Products',
    subcategory: 'Meat',
    basePrice: 385,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍖',
    description: 'Fresh mutton meat, rich flavor.',
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2-3 days',
    nutritionHighlight: 'High in iron and zinc',
  },
  {
    id: 'goat-meat',
    name: 'Goat Meat',
    category: 'Animal Products',
    subcategory: 'Meat',
    basePrice: 365,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍖',
    description: 'Fresh goat meat, lean and tender.',
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2-3 days',
    nutritionHighlight: 'Lower fat than mutton',
  },

  // Eggs & Dairy
  {
    id: 'milk',
    name: 'Milk',
    category: 'Animal Products',
    subcategory: 'Eggs & Dairy',
    basePrice: 48,
    unit: 'liter',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&q=80',
    priceChange: '+1%',
    emoji: '🥛',
    description: 'Fresh cow milk, daily essential.',
    tags: ['bulk'],
    minOrderQty: 5,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 days',
    nutritionHighlight: 'Calcium and protein rich',
  },
  {
    id: 'yogurt',
    name: 'Yogurt',
    category: 'Animal Products',
    subcategory: 'Eggs & Dairy',
    basePrice: 65,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1571212515416-fef01fc43637?w=400&q=80',
    priceChange: '+2%',
    emoji: '🫙',
    description: 'Fresh yogurt, probiotic rich.',
    minOrderQty: 1,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '5-7 days',
    nutritionHighlight: 'Probiotics for gut health',
  },

  // Additional Vegetables (Extended)
  {
    id: 'okra-extra',
    name: 'Okra',
    category: 'Vegetables',
    subcategory: 'Specialty Vegetables',
    basePrice: 48,
    unit: 'kg',
    demand: 'High',
    season: 'Mar-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1584399167389-084d11a309a7?w=400&q=80',
    priceChange: '+2%',
    emoji: '🫛',
    description: 'Fresh okra, tender pods perfect for frying.',
    tags: ['seasonal'],
    harvestMonth: [3, 4, 5, 6, 7, 8, 9, 10],
    storageLife: '2-3 days',
    nutritionHighlight: 'Fiber and antioxidants',
  },
  {
    id: 'ash-gourd',
    name: 'Ash Gourd',
    category: 'Vegetables',
    subcategory: 'Gourds & Squash',
    basePrice: 32,
    unit: 'kg',
    demand: 'Medium',
    season: 'Jul-Nov',
    imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥒',
    description: 'Pale green ash gourd, light and cooling.',
    tags: ['seasonal'],
    harvestMonth: [7, 8, 9, 10, 11],
    storageLife: '2-3 weeks',
    nutritionHighlight: 'Cooling properties for summer',
  },
  {
    id: 'ivy-gourd',
    name: 'Ivy Gourd',
    category: 'Vegetables',
    subcategory: 'Gourds & Squash',
    basePrice: 52,
    unit: 'kg',
    demand: 'Medium',
    season: 'Apr-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=400&q=80',
    priceChange: '+3%',
    emoji: '🥒',
    description: 'Tiny ivy gourds, tender and flavorful.',
    tags: ['seasonal'],
    harvestMonth: [4, 5, 6, 7, 8, 9, 10],
    storageLife: '3-4 days',
    nutritionHighlight: 'Low calorie, fiber rich',
  },
  {
    id: 'drumstick',
    name: 'Drumstick (Moringa)',
    category: 'Vegetables',
    subcategory: 'Specialty Vegetables',
    basePrice: 45,
    unit: 'bundles',
    demand: 'High',
    season: 'Dec-Jun',
    imageUrl: 'https://images.unsplash.com/photo-1546471180-9d74f86e0d38?w=400&q=80',
    priceChange: '+4%',
    emoji: '🌿',
    description: 'Fresh drumstick, superfood vegetable.',
    tags: ['seasonal'],
    harvestMonth: [12, 1, 2, 3, 4, 5, 6],
    storageLife: '2-3 days',
    nutritionHighlight: '13 essential nutrients',
  },

  // Additional Fruits (Extended)
  {
    id: 'peach',
    name: 'Peach',
    category: 'Fruits',
    subcategory: 'Premium Fruits',
    basePrice: 135,
    unit: 'kg',
    demand: 'Low',
    season: 'Mar-Jun',
    imageUrl: 'https://images.unsplash.com/photo-1589300534738-b7d11da8f4b5?w=400&q=80',
    priceChange: '+8%',
    emoji: '🍑',
    description: 'Sweet peaches, juicy and aromatic.',
    tags: ['premium', 'seasonal'],
    harvestMonth: [3, 4, 5, 6],
    storageLife: '5-7 days',
    nutritionHighlight: 'Vitamin C and niacin',
  },
  {
    id: 'plum',
    name: 'Plum',
    category: 'Fruits',
    subcategory: 'Premium Fruits',
    basePrice: 125,
    unit: 'kg',
    demand: 'Low',
    season: 'Feb-May',
    imageUrl: 'https://images.unsplash.com/photo-1526283538-b5f1f17b7f87?w=400&q=80',
    priceChange: '+7%',
    emoji: '🫐',
    description: 'Purple plums, sweet and juicy.',
    tags: ['premium', 'seasonal'],
    harvestMonth: [2, 3, 4, 5],
    storageLife: '3-5 days',
    nutritionHighlight: 'Sorbitol for digestion',
  },
  {
    id: 'litchi',
    name: 'Litchi',
    category: 'Fruits',
    subcategory: 'Tropical',
    basePrice: 95,
    unit: 'kg',
    demand: 'Medium',
    season: 'May-Jul',
    imageUrl: 'https://images.unsplash.com/photo-1596591201291-56974ae4dbf1?w=400&q=80',
    priceChange: '+9%',
    emoji: '🍒',
    description: 'Fresh litchis, sweet and perfumed.',
    tags: ['seasonal'],
    harvestMonth: [5, 6, 7],
    storageLife: '2-3 days',
    nutritionHighlight: 'Vitamin C and copper',
  },
  {
    id: 'mulberry',
    name: 'Mulberry',
    category: 'Fruits',
    subcategory: 'Berries',
    basePrice: 185,
    unit: 'kg',
    demand: 'Low',
    season: 'May-Jul',
    imageUrl: 'https://images.unsplash.com/photo-1600185365483-26d7a7cc43e4?w=400&q=80',
    priceChange: '+10%',
    emoji: '🫐',
    description: 'Sweet mulberries, antioxidant rich.',
    tags: ['premium', 'seasonal'],
    harvestMonth: [5, 6, 7],
    storageLife: '1-2 days',
    nutritionHighlight: 'Anthocyanins for brain health',
  },
  {
    id: 'custard-apple',
    name: 'Custard Apple',
    category: 'Fruits',
    subcategory: 'Tropical',
    basePrice: 75,
    unit: 'kg',
    demand: 'High',
    season: 'Aug-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1585519634034-7cf8d7cfcaa7?w=400&q=80',
    priceChange: '+6%',
    emoji: '🍈',
    description: 'Creamy custard apples, tropical favorite.',
    tags: ['seasonal'],
    harvestMonth: [8, 9, 10],
    storageLife: '2-3 days',
    nutritionHighlight: 'Copper and fiber rich',
  },
  {
    id: 'sapota',
    name: 'Sapota',
    category: 'Fruits',
    subcategory: 'Tropical',
    basePrice: 65,
    unit: 'kg',
    demand: 'Medium',
    season: 'Jul-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1585519634034-7cf8d7cfcaa7?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍌',
    description: 'Brown sapota, sweet and creamy.',
    tags: ['seasonal'],
    harvestMonth: [7, 8, 9, 10],
    storageLife: '3-4 days',
    nutritionHighlight: 'Iron and vitamin A',
  },

  // Additional Greens & Herbs
  {
    id: 'curry-leaves',
    name: 'Curry Leaves',
    category: 'Greens',
    subcategory: 'Fresh Herbs',
    basePrice: 35,
    unit: 'bundles',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1615485276934-a65bfb2546ab?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌿',
    description: 'Fresh curry leaves, aromatic seasoning.',
    tags: ['bulk'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '5-7 days',
    nutritionHighlight: 'Antioxidants and minerals',
  },
  {
    id: 'basil',
    name: 'Basil',
    category: 'Greens',
    subcategory: 'Fresh Herbs',
    basePrice: 42,
    unit: 'bundles',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1615485276934-a65bfb2546ab?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌿',
    description: 'Fresh basil, sweet and aromatic herb.',
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '3-4 days',
    nutritionHighlight: 'Eugenol for anti-inflammatory',
  },

  // Spices & Condiments (Major Addition)
  {
    id: 'turmeric',
    name: 'Turmeric Powder',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 125,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌾',
    description: 'Pure turmeric powder, golden spice.',
    tags: ['organic'],
    minOrderQty: 1,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Curcumin for inflammation',
  },
  {
    id: 'red-chili',
    name: 'Red Chili Powder',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 95,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400&q=80',
    priceChange: '+4%',
    emoji: '🌶️',
    description: 'Red chili powder, hot and spicy.',
    tags: ['organic'],
    minOrderQty: 1,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Capsaicin for metabolism',
  },
  {
    id: 'coriander-powder',
    name: 'Coriander Powder',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 85,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'Coriander powder, aromatic spice.',
    tags: ['organic'],
    minOrderQty: 1,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Digestive aid',
  },
  {
    id: 'cumin-powder',
    name: 'Cumin Powder',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 95,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1607113256158-56a934936ef6?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'Cumin powder, warm spice.',
    tags: ['organic'],
    minOrderQty: 1,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Aids iron absorption',
  },
  {
    id: 'black-pepper',
    name: 'Black Pepper',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 185,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=400&q=80',
    priceChange: '+5%',
    emoji: '🫑',
    description: 'Black peppercorns, pungent spice.',
    tags: ['organic'],
    minOrderQty: 1,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2 years',
    nutritionHighlight: 'Piperine enhances absorption',
  },
  {
    id: 'garam-masala',
    name: 'Garam Masala',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 125,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌾',
    description: 'Garam masala blend, warm spices.',
    tags: ['organic'],
    minOrderQty: 1,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Spice blend with multiple benefits',
  },
  {
    id: 'jaggery',
    name: 'Jaggery',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 68,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+2%',
    emoji: '🍬',
    description: 'Brown jaggery, natural sweetener.',
    tags: ['organic'],
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Minerals and iron content',
  },
  {
    id: 'sesame-oil',
    name: 'Sesame Oil',
    category: 'Grocery',
    subcategory: 'Oils & Fats',
    basePrice: 285,
    unit: 'liter',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=400&q=80',
    priceChange: '+4%',
    emoji: '🫗',
    description: 'Sesame oil, nutty and aromatic.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Linoleic acid for heart health',
  },

  // Additional Animal Products
  {
    id: 'quail-eggs',
    name: 'Quail Eggs',
    category: 'Animal Products',
    subcategory: 'Poultry',
    basePrice: 2,
    unit: 'pieces',
    demand: 'Low',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥚',
    description: 'Tiny quail eggs, premium nutrition.',
    tags: ['premium'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2-3 weeks',
    nutritionHighlight: 'Rich in proteins and choline',
  },
  {
    id: 'shrimp',
    name: 'Shrimp',
    category: 'Animal Products',
    subcategory: 'Seafood',
    basePrice: 385,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1580822261290-991b38693d1b?w=400&q=80',
    priceChange: '+5%',
    emoji: '🦐',
    description: 'Fresh shrimp, delicate seafood.',
    tags: ['premium'],
    minOrderQty: 1,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 day',
    nutritionHighlight: 'Selenium and astaxanthin',
  },
  {
    id: 'crab',
    name: 'Crab',
    category: 'Animal Products',
    subcategory: 'Seafood',
    basePrice: 425,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1580822261290-991b38693d1b?w=400&q=80',
    priceChange: '+6%',
    emoji: '🦀',
    description: 'Fresh crab, delicacy meat.',
    tags: ['premium'],
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 day',
    nutritionHighlight: 'Zinc and copper rich',
  },

  // Additional Spices Collection
  {
    id: 'fenugreek-seed',
    name: 'Fenugreek Seeds',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 145,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌾',
    description: 'Fenugreek seeds, bitter spice.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Trigonelline lowers blood sugar',
  },
  {
    id: 'fennel-seeds',
    name: 'Fennel Seeds',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 155,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'Fennel seeds, sweet and aromatic.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Anethole for digestion',
  },
  {
    id: 'mustard-seeds',
    name: 'Mustard Seeds',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 135,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'Black mustard seeds, pungent spice.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Selenium and omega-3',
  },
  {
    id: 'cardamom',
    name: 'Cardamom',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 285,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+4%',
    emoji: '🌾',
    description: 'Green cardamom pods, aromatic spice.',
    tags: ['premium'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 years',
    nutritionHighlight: 'Cinneole for digestion',
  },
  {
    id: 'cloves',
    name: 'Cloves',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 325,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌾',
    description: 'Cloves, warm and peppery spice.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 years',
    nutritionHighlight: 'Eugenol for antioxidants',
  },
  {
    id: 'cinnamon',
    name: 'Cinnamon',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 215,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'Cinnamon sticks, sweet spice.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2 years',
    nutritionHighlight: 'Cinnamaldehyde regulates blood sugar',
  },
  {
    id: 'bay-leaf',
    name: 'Bay Leaf',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 175,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+1%',
    emoji: '🌿',
    description: 'Dried bay leaves, aromatic herb.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Linalool for calming',
  },
  {
    id: 'star-anise',
    name: 'Star Anise',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 245,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌾',
    description: 'Star anise, licorice-like flavor.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 years',
    nutritionHighlight: 'Anethole for respiratory health',
  },

  // Additional Rice & Grains
  {
    id: 'jasmine-rice',
    name: 'Jasmine Rice',
    category: 'Grocery',
    subcategory: 'Grains & Staples',
    basePrice: 95,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌾',
    description: 'Jasmine rice, fragrant long grain.',
    tags: ['organic'],
    minOrderQty: 5,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Carbohydrates with aroma',
  },
  {
    id: 'brown-rice',
    name: 'Brown Rice',
    category: 'Grocery',
    subcategory: 'Grains & Staples',
    basePrice: 65,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'Brown rice, whole grain nutrition.',
    tags: ['organic'],
    minOrderQty: 5,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Manganese and magnesium',
  },
  {
    id: 'ragi-flour',
    name: 'Ragi Flour',
    category: 'Grocery',
    subcategory: 'Grains & Staples',
    basePrice: 72,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'Ragi flour, millets nutritious.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '3 months',
    nutritionHighlight: 'Calcium and fiber rich',
  },
  {
    id: 'oats',
    name: 'Rolled Oats',
    category: 'Grocery',
    subcategory: 'Grains & Staples',
    basePrice: 85,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'Rolled oats, healthy breakfast grain.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Beta-glucan for heart health',
  },

  // Additional Pulses
  {
    id: 'toor-dal',
    name: 'Toor Dal',
    category: 'Grocery',
    subcategory: 'Pulses',
    basePrice: 165,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+3%',
    emoji: '🫘',
    description: 'Toor dal, yellow pigeon peas.',
    tags: ['bulk'],
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Protein and folate',
  },
  {
    id: 'urad-dal',
    name: 'Urad Dal',
    category: 'Grocery',
    subcategory: 'Pulses',
    basePrice: 155,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+2%',
    emoji: '🫘',
    description: 'Urad dal, black lentils.',
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Iron and protein',
  },
  {
    id: 'masoor-dal',
    name: 'Masoor Dal',
    category: 'Grocery',
    subcategory: 'Pulses',
    basePrice: 125,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+2%',
    emoji: '🫘',
    description: 'Masoor dal, red lentils.',
    tags: ['bulk'],
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Fiber and polyphenols',
  },
  {
    id: 'chickpea',
    name: 'Chickpea',
    category: 'Grocery',
    subcategory: 'Pulses',
    basePrice: 145,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+3%',
    emoji: '🫘',
    description: 'Chickpeas, protein powerhouse.',
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 years',
    nutritionHighlight: 'Plant protein and manganese',
  },
  {
    id: 'black-bean',
    name: 'Black Beans',
    category: 'Grocery',
    subcategory: 'Pulses',
    basePrice: 155,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+2%',
    emoji: '🫘',
    description: 'Black beans, nutritious legume.',
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Anthocyanins and fiber',
  },

  // Additional Vegetables (Extended)
  {
    id: 'white-pumpkin',
    name: 'White Pumpkin',
    category: 'Vegetables',
    subcategory: 'Gourds & Squash',
    basePrice: 28,
    unit: 'kg',
    demand: 'Low',
    season: 'Jul-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1584622666223-620f9ff37f3f?w=400&q=80',
    priceChange: '+1%',
    emoji: '🎃',
    description: 'White pumpkin, mild and sweet.',
    tags: ['seasonal'],
    harvestMonth: [7, 8, 9, 10],
    storageLife: '2-3 weeks',
    nutritionHighlight: 'Vitamins and minerals',
  },
  {
    id: 'french-beans',
    name: 'French Beans',
    category: 'Vegetables',
    subcategory: 'Legumes',
    basePrice: 52,
    unit: 'kg',
    demand: 'Medium',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1545188207-d05fd48f5da6?w=400&q=80',
    priceChange: '+3%',
    emoji: '🫘',
    description: 'Tender French beans, delicate.',
    tags: ['seasonal'],
    harvestMonth: [10, 11, 12, 1, 2, 3],
    storageLife: '4-5 days',
    nutritionHighlight: 'Vitamins and minerals',
  },
  {
    id: 'long-beans',
    name: 'Long Beans',
    category: 'Vegetables',
    subcategory: 'Legumes',
    basePrice: 45,
    unit: 'kg',
    demand: 'High',
    season: 'May-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1545188207-d05fd48f5da6?w=400&q=80',
    priceChange: '+2%',
    emoji: '🫘',
    description: 'Long beans, tender and crunchy.',
    tags: ['seasonal'],
    harvestMonth: [5, 6, 7, 8, 9, 10],
    storageLife: '2-3 days',
    nutritionHighlight: 'Fiber and nutrients',
  },
  {
    id: 'sweet-potato',
    name: 'Sweet Potato',
    category: 'Vegetables',
    subcategory: 'Root Vegetables',
    basePrice: 35,
    unit: 'kg',
    demand: 'Medium',
    season: 'Sep-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1584622666223-620f9ff37f3f?w=400&q=80',
    priceChange: '+2%',
    emoji: '🍠',
    description: 'Sweet potato, orange and nutritious.',
    tags: ['seasonal'],
    harvestMonth: [9, 10, 11, 12, 1, 2, 3],
    storageLife: '1-2 weeks',
    nutritionHighlight: 'Beta-carotene and fiber',
  },
  {
    id: 'bottle-gourd-long',
    name: 'Long Bottle Gourd',
    category: 'Vegetables',
    subcategory: 'Gourds & Squash',
    basePrice: 22,
    unit: 'kg',
    demand: 'High',
    season: 'Apr-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=400&q=80',
    priceChange: '+1%',
    emoji: '🥒',
    description: 'Long bottle gourd variant.',
    tags: ['seasonal'],
    harvestMonth: [4, 5, 6, 7, 8, 9, 10],
    storageLife: '1-2 weeks',
    nutritionHighlight: 'Hydrating and cooling',
  },

  // Additional Fruits
  {
    id: 'jamun',
    name: 'Jamun (Black Plum)',
    category: 'Fruits',
    subcategory: 'Tropical',
    basePrice: 85,
    unit: 'kg',
    demand: 'Medium',
    season: 'Jun-Aug',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80',
    priceChange: '+5%',
    emoji: '🫐',
    description: 'Purple jamun, sweet and astringent.',
    tags: ['seasonal'],
    harvestMonth: [6, 7, 8],
    storageLife: '2-3 days',
    nutritionHighlight: 'Anthocyanins for heart',
  },
  {
    id: 'fig',
    name: 'Fresh Figs',
    category: 'Fruits',
    subcategory: 'Premium Fruits',
    basePrice: 165,
    unit: 'kg',
    demand: 'Low',
    season: 'Jul-Sep',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80',
    priceChange: '+8%',
    emoji: '🍑',
    description: 'Fresh figs, sweet and nutritious.',
    tags: ['premium', 'seasonal'],
    harvestMonth: [7, 8, 9],
    storageLife: '2-3 days',
    nutritionHighlight: 'Fiber and minerals',
  },
  {
    id: 'grapefruit',
    name: 'Grapefruit',
    category: 'Fruits',
    subcategory: 'Citrus',
    basePrice: 55,
    unit: 'kg',
    demand: 'Low',
    season: 'Nov-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍊',
    description: 'Pink grapefruit, citrus favorite.',
    tags: ['seasonal'],
    harvestMonth: [11, 12, 1, 2, 3],
    storageLife: '2-3 weeks',
    nutritionHighlight: 'Vitamin C and lycopene',
  },

  // Additional Herbs
  {
    id: 'thyme',
    name: 'Thyme',
    category: 'Greens',
    subcategory: 'Fresh Herbs',
    basePrice: 48,
    unit: 'bundles',
    demand: 'Low',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1615485276934-a65bfb2546ab?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌿',
    description: 'Fresh thyme, aromatic herb.',
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 week',
    nutritionHighlight: 'Thymol for respiratory health',
  },
  {
    id: 'oregano',
    name: 'Oregano',
    category: 'Greens',
    subcategory: 'Fresh Herbs',
    basePrice: 52,
    unit: 'bundles',
    demand: 'Low',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1615485276934-a65bfb2546ab?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌿',
    description: 'Fresh oregano, Mediterranean herb.',
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 week',
    nutritionHighlight: 'Rosmarinic acid antioxidant',
  },

  // Nuts & Dried Fruits
  {
    id: 'almonds',
    name: 'Almonds',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 425,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌰',
    description: 'Premium almonds, rich in nutrients.',
    tags: ['premium'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Vitamin E and magnesium',
  },
  {
    id: 'cashew',
    name: 'Cashew Nuts',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 485,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+4%',
    emoji: '🥜',
    description: 'Premium cashew nuts, rich taste.',
    tags: ['premium'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Copper and zinc',
  },
  {
    id: 'walnut',
    name: 'Walnuts',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 445,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌰',
    description: 'Walnuts, omega-3 rich brain food.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'ALA omega-3 for brain',
  },
  {
    id: 'peanut',
    name: 'Peanuts',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 185,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥜',
    description: 'Raw peanuts, protein-rich legume.',
    tags: ['bulk'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Plant protein and resveratrol',
  },
  {
    id: 'dates',
    name: 'Dates',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 245,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍯',
    description: 'Dried dates, natural sweetener.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Fiber and natural sugars',
  },
  {
    id: 'raisins',
    name: 'Raisins',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 185,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80',
    priceChange: '+2%',
    emoji: '🍇',
    description: 'Dried raisins, sweet and chewy.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Iron and antioxidants',
  },
  {
    id: 'dried-apricot',
    name: 'Dried Apricots',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 225,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍑',
    description: 'Dried apricots, tangy sweetness.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Beta-carotene and fiber',
  },

  // Additional Microgreens (Extended)
  {
    id: 'buckwheat-sprouts',
    name: 'Buckwheat Sprouts',
    category: 'Microgreens',
    subcategory: 'Premium Microgreens',
    basePrice: 275,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1631915382946-48416bdf67f3?w=400&q=80',
    priceChange: '+5%',
    emoji: '🌱',
    description: 'Buckwheat sprouts, mild flavor.',
    tags: ['premium'],
    storageLife: '1 week',
    nutritionHighlight: 'Rutin for circulation',
  },
  {
    id: 'mung-sprouts',
    name: 'Mung Sprouts',
    category: 'Microgreens',
    subcategory: 'Legume Sprouts',
    basePrice: 245,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1631915382946-48416bdf67f3?w=400&q=80',
    priceChange: '+4%',
    emoji: '🌱',
    description: 'Fresh mung sprouts, crispy.',
    storageLife: '3-5 days',
    nutritionHighlight: 'Plant enzymes for digestion',
  },
  {
    id: 'moong-sprouts',
    name: 'Moong Sprouts',
    category: 'Microgreens',
    subcategory: 'Legume Sprouts',
    basePrice: 235,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1631915382946-48416bdf67f3?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌱',
    description: 'Moong bean sprouts, nutritious.',
    storageLife: '3-4 days',
    nutritionHighlight: 'Arginine for immunity',
  },

  // Additional Animal Products
  {
    id: 'lamb-meat',
    name: 'Lamb',
    category: 'Animal Products',
    subcategory: 'Meat',
    basePrice: 405,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍖',
    description: 'Fresh lamb meat, tender cuts.',
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '2-3 days',
    nutritionHighlight: 'Zinc and carnitine',
  },
  {
    id: 'duck-meat',
    name: 'Duck',
    category: 'Animal Products',
    subcategory: 'Poultry',
    basePrice: 265,
    unit: 'kg',
    demand: 'Low',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&q=80',
    priceChange: '+5%',
    emoji: '🦆',
    description: 'Fresh duck meat, premium poultry.',
    tags: ['premium'],
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 days',
    nutritionHighlight: 'Selenium and niacin',
  },
  {
    id: 'guinea-fowl',
    name: 'Guinea Fowl',
    category: 'Animal Products',
    subcategory: 'Poultry',
    basePrice: 245,
    unit: 'kg',
    demand: 'Low',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&q=80',
    priceChange: '+4%',
    emoji: '🐔',
    description: 'Guinea fowl, lean poultry.',
    tags: ['premium'],
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 days',
    nutritionHighlight: 'Omega-3 fatty acids',
  },
  {
    id: 'fish-salmon',
    name: 'Fish - Salmon',
    category: 'Animal Products',
    subcategory: 'Seafood',
    basePrice: 325,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1580822261290-991b38693d1b?w=400&q=80',
    priceChange: '+6%',
    emoji: '🐟',
    description: 'Fresh salmon, omega-3 rich.',
    tags: ['premium'],
    minOrderQty: 1,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 day',
    nutritionHighlight: 'Astaxanthin for heart',
  },
  {
    id: 'fish-tuna',
    name: 'Fish - Tuna',
    category: 'Animal Products',
    subcategory: 'Seafood',
    basePrice: 285,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1580822261290-991b38693d1b?w=400&q=80',
    priceChange: '+4%',
    emoji: '🐟',
    description: 'Fresh tuna, protein rich fish.',
    minOrderQty: 1,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 day',
    nutritionHighlight: 'Selenium and vitamin D',
  },
  {
    id: 'lobster',
    name: 'Lobster',
    category: 'Animal Products',
    subcategory: 'Seafood',
    basePrice: 485,
    unit: 'kg',
    demand: 'Low',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1580822261290-991b38693d1b?w=400&q=80',
    priceChange: '+8%',
    emoji: '🦞',
    description: 'Fresh lobster, delicacy.',
    tags: ['premium'],
    minOrderQty: 1,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 day',
    nutritionHighlight: 'Copper and selenium',
  },

  // Additional Vegetables (Final Extension)
  {
    id: 'bitter-gourd-green',
    name: 'Green Bitter Gourd',
    category: 'Vegetables',
    subcategory: 'Gourds & Squash',
    basePrice: 52,
    unit: 'kg',
    demand: 'High',
    season: 'May-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1584622666223-620f9ff37f3f?w=400&q=80',
    priceChange: '+3%',
    emoji: '🥒',
    description: 'Green bitter gourd, medicinal.',
    harvestMonth: [5, 6, 7, 8, 9, 10],
    storageLife: '3-4 days',
    nutritionHighlight: 'Bitter compounds for health',
  },
  {
    id: 'ridge-gourd-tender',
    name: 'Tender Ridge Gourd',
    category: 'Vegetables',
    subcategory: 'Gourds & Squash',
    basePrice: 32,
    unit: 'kg',
    demand: 'Medium',
    season: 'May-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥒',
    description: 'Tender young ridge gourds.',
    tags: ['seasonal'],
    harvestMonth: [5, 6, 7, 8, 9, 10],
    storageLife: '2-3 days',
    nutritionHighlight: 'Cooling summer vegetable',
  },
  {
    id: 'lauki',
    name: 'Lauki (Bottle Gourd)',
    category: 'Vegetables',
    subcategory: 'Gourds & Squash',
    basePrice: 25,
    unit: 'kg',
    demand: 'Medium',
    season: 'Apr-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=400&q=80',
    priceChange: '+1%',
    emoji: '🍈',
    description: 'Lauki for summer, cooling.',
    tags: ['seasonal'],
    harvestMonth: [4, 5, 6, 7, 8, 9, 10],
    storageLife: '1-2 weeks',
    nutritionHighlight: 'Diuretic properties',
  },
  {
    id: 'pumpkin-tender',
    name: 'Tender Pumpkin',
    category: 'Vegetables',
    subcategory: 'Gourds & Squash',
    basePrice: 38,
    unit: 'kg',
    demand: 'Low',
    season: 'Aug-Nov',
    imageUrl: 'https://images.unsplash.com/photo-1584622666223-620f9ff37f3f?w=400&q=80',
    priceChange: '+2%',
    emoji: '🎃',
    description: 'Young tender pumpkin.',
    tags: ['seasonal'],
    harvestMonth: [8, 9, 10, 11],
    storageLife: '1 week',
    nutritionHighlight: 'Carotenoids for vision',
  },

  // Final Batch: Additional Fruits & Specialty Items
  {
    id: 'coconut-fresh',
    name: 'Fresh Young Coconut',
    category: 'Fruits',
    subcategory: 'Tropical',
    basePrice: 52,
    unit: 'pieces',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥥',
    description: 'Young tender coconut water.',
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 week',
    nutritionHighlight: 'Electrolytes and hydration',
  },
  {
    id: 'pear',
    name: 'Pear',
    category: 'Fruits',
    subcategory: 'Premium Fruits',
    basePrice: 145,
    unit: 'kg',
    demand: 'Low',
    season: 'Aug-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80',
    priceChange: '+6%',
    emoji: '🍐',
    description: 'Sweet pears, buttery texture.',
    tags: ['premium', 'seasonal'],
    harvestMonth: [8, 9, 10],
    storageLife: '5-7 days',
    nutritionHighlight: 'Fiber and boron for bones',
  },
  {
    id: 'jujube',
    name: 'Jujube (Indian Date)',
    category: 'Fruits',
    subcategory: 'Tropical',
    basePrice: 55,
    unit: 'kg',
    demand: 'Low',
    season: 'Oct-Jan',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍎',
    description: 'Jujubes, crispy and sweet.',
    tags: ['seasonal'],
    harvestMonth: [10, 11, 12, 1],
    storageLife: '1-2 weeks',
    nutritionHighlight: 'Vitamin C booster',
  },
  {
    id: 'mint-dried',
    name: 'Dried Mint',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 165,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌿',
    description: 'Dried mint leaves, cooling.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Menthol for digestion',
  },
  {
    id: 'chaat-masala',
    name: 'Chaat Masala',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 95,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'Chaat masala spice blend.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Tangy spice blend',
  },
  {
    id: 'amchur',
    name: 'Amchur (Dried Mango Powder)',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 125,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+3%',
    emoji: '🥭',
    description: 'Dried mango powder, tangy.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Sour flavor without salt',
  },
  {
    id: 'kasuri-methi',
    name: 'Kasuri Methi (Dried Fenugreek)',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 145,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'Dried methi leaves, aromatic.',
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Antidiabetic properties',
  },
  {
    id: 'sunflower-seeds',
    name: 'Sunflower Seeds',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 95,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌻',
    description: 'Sunflower seeds, nutritious.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Vitamin E and selenium',
  },
  {
    id: 'pumpkin-seeds',
    name: 'Pumpkin Seeds',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 185,
    unit: 'kg',
    demand: 'Low',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+3%',
    emoji: '🎃',
    description: 'Pumpkin seeds, zinc rich.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '6 months',
    nutritionHighlight: 'Magnesium and zinc',
  },
  {
    id: 'sesame-seeds',
    name: 'Sesame Seeds',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 165,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'White sesame seeds, nutty.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'Calcium and lignans',
  },
  {
    id: 'flax-seeds',
    name: 'Flax Seeds',
    category: 'Grocery',
    subcategory: 'Condiments',
    basePrice: 145,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1609535146778-786490249524?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌾',
    description: 'Flax seeds, omega-3 rich.',
    tags: ['organic'],
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1 year',
    nutritionHighlight: 'ALA and lignans',
  },

  // Final Animal Products
  {
    id: 'turkey',
    name: 'Turkey',
    category: 'Animal Products',
    subcategory: 'Poultry',
    basePrice: 255,
    unit: 'kg',
    demand: 'Low',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&q=80',
    priceChange: '+3%',
    emoji: '🦃',
    description: 'Turkey meat, lean protein.',
    tags: ['premium'],
    minOrderQty: 2,
    harvestMonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    storageLife: '1-2 days',
    nutritionHighlight: 'Selenium and B vitamins',
  },
];

const REMOTE_IMAGE_FALLBACK_IDS = new Set(['fenugreek-seed']);

export const PRODUCTS: Product[] = RAW_PRODUCTS.map((product) => ({
  ...product,
  imageUrl: REMOTE_IMAGE_FALLBACK_IDS.has(product.id)
    ? product.imageUrl
    : `/product-images/catalog/${product.id}.jpg`,
}));

/**
 * Helper function to get products by category
 */
export const getProductsByCategory = (category: MainCategory): Product[] => {
  return PRODUCTS.filter((p) => p.category === category);
};

/**
 * Helper function to get products by subcategory
 */
export const getProductsBySubcategory = (subcategory: SubcategoryType): Product[] => {
  return PRODUCTS.filter((p) => p.subcategory === subcategory);
};

/**
 * Helper function to get top products by demand
 */
export const getTopByDemand = (products: Product[] = PRODUCTS, count: number = 12): Product[] => {
  const demandOrder = { 'Very High': 4, High: 3, Medium: 2, Low: 1 };
  return [...products]
    .sort((a, b) => demandOrder[b.demand as keyof typeof demandOrder] - demandOrder[a.demand as keyof typeof demandOrder])
    .slice(0, count);
};

/**
 * Helper function to filter in-season products
 */
export const filterInSeason = (products: Product[] = PRODUCTS): Product[] => {
  const currentMonth = new Date().getMonth() + 1;
  return products.filter((p) => {
    if (!p.harvestMonth) return true;
    return p.harvestMonth.includes(currentMonth);
  });
};

/**
 * Get all unique categories from products
 */
export const getAllCategories = (): MainCategory[] => {
  const categories = new Set(PRODUCTS.map((p) => p.category));
  return Array.from(categories) as MainCategory[];
};

/**
 * Search products by name (case-insensitive)
 */
export const searchProducts = (query: string): Product[] => {
  const lowerQuery = query.toLowerCase();
  return PRODUCTS.filter((p) =>
    p.name.toLowerCase().includes(lowerQuery) ||
    p.category.toLowerCase().includes(lowerQuery) ||
    p.subcategory.toLowerCase().includes(lowerQuery)
  );
};
